### PR TITLE
Fix includes

### PR DESCRIPTION
**Pull request by mausquirk**
In order to be able to compile waspmote applications outside waspmote-ide (for example with avr-gcc or in eclipse ... etc.) the includes need to defined correctly:

```
    #include <header.h> // for header files in search path (-I option)
    #include "header.h" // for local files in the same directory
```

This does not harm the build within waspmote-ide in any kind. All example codes in waspmote-ide still compiles.

### CODE REVIEW

**Comment by mausquirk** [comment]
@Libelium Any news on this PR? Do I need to provide you more test results?

**Comment by Libelium** [comment]
Mausquirk,

Thanks for your comments. We will take your suggestion into account for the next API versions.

Regards

**Comment by mausquirk** [comment]
Libelium seems to constantly ignore any improvements/suggestions from the community. This behaviour won't improve your product nor your customer's satisfaction.

**Comment by Libelium** [comment]
Hi mausquirk, we're sorry if we didn't correct all the API with your suggestions, please next time you put your suggestions as Issues and we will take note of them.

Regards.

**Pull request closed without merging**
