### PR TITLE
Small error return error fix in WaspSD::Init()

### PR DESCRIPTION
**Pull request by avdwoude**
Currently WaspSD::Init() uses INIT_FAILED twice. The in-line documentation mentions VOLUME_FAILED, which is not actually used. This small fix changes one of the INIT_FAILED uses to VOLUME_FAILED instead. This makes it easier to differentiate all the failures of WaspSD::Init().

### CODE REVIEW

**Comment by avdwoude** [comment]
I have just created an account on the Libelium Forum. That request is in review, so I am not yet able to report about this pull request on the Forum as suggested by your documentation. If you require to use your unstable branch instead, let me know. As the change is really minor, I thought your stable branch would be ok.

**Comment by Libelium** [comment]
Hi avdwoude,

Thanks for your contribution.

We're sorry but we don't check the pull requests at GitHub, we will take a look at your changes and we will study to include the changes for the next API version. 

Please for next time you want to propose a change on the API you write at the issues tab and we will take a look at it.

Regards

**Comment by avdwoude** [comment]
Thanks for the feedback. Next time I will create an issue instead. I do also suggest you update your documentation (link below) on providing patches and requiring a new issue instead of a pull request. For this pull request I followed the Libelium documentation found at:

"How upload your code to the Waspmote API Unstable repository"
https://www.libelium.com/forum/viewtopic.php?t=10132

Thanks!

**Comment by Libelium** [comment]
Thanks again for your colaboration, that topic is out-of-date and we're not working anymore with GitHub on that way.
 
We will correct it as soon as possible.

Regards

**Pull request closed without merging**
